Sources / Install simplified

diff --git a/image/openkarotz/install b/image/openkarotz/install
--- a/image/openkarotz/install
+++ b/image/openkarotz/install
@@ -1,6 +1,6 @@
 #!/bin/bash
-
-source /mnt/usbkey/openkarotz/setup.inc
+CURRDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+source ${CURRDIR}/setup.inc
 
 function Log {
  #TAG=$1
@@ -34,351 +34,53 @@ WHITE=4FFF68
 YELLOW=75FF00
 
 
-SURL="OLDVERSION"
-
-# Checking Forced Update
-FU=${URLParam[force]}
-UU=${URLParam[usb]}
-
-if [ "$FU" == "1" ] || [ "$1" == "1" ]; then
- rm -f $TDIR/ok.version >>/dev/null 2>>/dev/null
+if [ ! -d $SOURCES_CNF ]; then
+   Log  "[INSTALL]"  "$SOURCES_CNF NOT FOUND"
+   exit 1
 fi
 
-# Enable Logs at next reboot
-# Log Install Message in different file
-killall syslogd >>/dev/null 2>>/dev/null
-echo "" > /$CNF_DATADIR/install.log
-/sbin/syslogd -O /$CNF_DATADIR/install.log	>>/dev/null 2>>/dev/null
-touch /etc/conf/enable_syslogd >>/dev/null 2>>/dev/null
-Log  "[INSTALL]"  "Enabling Syslog"
-
-# Downloading Sound
-Log  "[INSTALL]"  "Downloading sounds"
-cp ${RESSDIR}/install_start.mp3 /tmp/start.mp3
-cp ${RESSDIR}/install_end.mp3 /tmp/end.mp3
-
-Log  "[INSTALL]"  "Killing default process"
-killall immortaldog >>/dev/null 2>>/dev/null
-/karotz/bin/led -l $ORANGE -p "000000" -d 700 &
-killall led
-
-if [ -e "/tmp/start.mp3" ]; then
-  /usr/bin/madplay /tmp/start.mp3 >>/dev/null 2>>/dev/null
+if [ ! -d $SOURCES_TDIR ]; then
+   Log  "[INSTALL]"  "$SOURCES_TDIR NOT FOUND"
+   exit 1
 fi
 
-# Checking root Web
-if [ ! -d $TDIR ]; then
+echo "SOURCES_TDIR: ${SOURCES_TDIR}"
+echo "SOURCES_CNF: ${SOURCES_CNF}"
+
+Log  "[INSTALL]"  "CleanUP"
+if [ -d $TDIR ]; then
    Log  "[INSTALL]"  "Creating directory:$TDIR"
-   mkdir $TDIR >>/dev/null 2>>/dev/null
+   rm -fr $TDIR >>/dev/null 2>>/dev/null
    Log  "[INSTALL]"  "Result:$?"
 fi
 
-# Checking Data root
-if [ ! -d $CNF_DATADIR ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR"
-   mkdir $CNF_DATADIR >>/dev/null 2>>/dev/null
+if [ -d $TDIR ]; then
+   Log  "[INSTALL]"  "Creating directory:$TDIR"
+   rm -fr $TDIR >>/dev/null 2>>/dev/null
    Log  "[INSTALL]"  "Result:$?"
 fi
 
-# Checking cgi-bin
-if [ ! -d $TDIR/cgi-bin ]; then
-   Log  "[INSTALL]"  "Creating directory:$TDIR/cgi-bin"
-   mkdir $TDIR/cgi-bin >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
-fi   
+Log  "[INSTALL]"  "Copy"
+Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR"
+cp -fR ${SOURCES_CNF}/ ${CNF_DATADIR}/ >>/dev/null 2>>/dev/null
+Log  "[INSTALL]"  "Result:$?"
 
-# Checking images
-if [ ! -d $TDIR/images ]; then
-   Log  "[INSTALL]"  "Creating directory:$TDIR/images"
-   mkdir $TDIR/images >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
-fi
+Log  "[INSTALL]"  "Creating directory:$TDIR"
+cp -fR ${SOURCES_TDIR}/ ${TDIR}/ >>/dev/null 2>>/dev/null
+Log  "[INSTALL]"  "Result:$?"
 
-# Checking Snapshots
-if [ ! -d $CNF_DATADIR/Snapshots ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Snapshots"
-   mkdir $CNF_DATADIR/Snapshots >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
-fi
 
-if [ ! -L $TDIR/snapshots ]; then
-   rm -rf $TDIR/snapshots >>/dev/null 2>>/dev/null
-   ln -s $CNF_DATADIR/Snapshots $TDIR/snapshots >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Creating snapshots symbolic link" 
-fi
+Log  "[INSTALL]"  "Creating Links"
+ln -s $CNF_DATADIR/Snapshots $TDIR/snapshots  >>/dev/null 2>>/dev/null
+ln -s $CNF_DATADIR/Tmp $TDIR/tts_cache >>/dev/null 2>>/dev/null
 
-# --------------
-# Checking Tmp
-# --------------
-if [ ! -d $CNF_DATADIR/Tmp ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Tmp"
-   mkdir $CNF_DATADIR/Tmp >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
-fi
-   
-# --------------
-# Checking Run
-# --------------
-if [ ! -d $CNF_DATADIR/Run ]; then
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Run"
-   mkdir $CNF_DATADIR/Run >>/dev/null 2>>/dev/null
-   Log  "[INSTALL]"  "Result:$?"
-fi
+Log  "[INSTALL]"  "Managing Rights"
+chmod -R 755 $TDIR
 
-# --------------      
-# Checking Rfid
-# --------------
-if [ ! -d $CNF_DATADIR/Rfid ]; then 
-  Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Rfid"
-  mkdir $CNF_DATADIR/Rfid >>/dev/null 2>>/dev/null
-  Log  "[INSTALL]"  "Result:$?"
-fi
-
-# --------------         
-# Checking Sounds
-# --------------
-if [ ! -d $CNF_DATADIR/Sounds ]; then
- Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Sounds"
- mkdir $CNF_DATADIR/Sounds >>/dev/null 2>>/dev/null
- Log  "[INSTALL]"  "Result:$?"
-fi
-          
-# --------------  
-# Checking Stories
-# --------------
-if [ ! -d $CNF_DATADIR/Stories ]; then
- Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Stories"
- mkdir $CNF_DATADIR/Stories >>/dev/null 2>>/dev/null
- Log  "[INSTALL]"  "Result:$?"
-fi
-
-# --------------
-# Checking Voice
-# --------------
-if [ ! -d $CNF_DATADIR/Voice ]; then
- Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Voice"
- mkdir $CNF_DATADIR/Voice >>/dev/null 2>>/dev/null
- Log  "[INSTALL]"  "Result:$?"
-fi
-
-# --------------
-# Checking Moods
-# --------------
-if [ ! -d $CNF_DATADIR/Moods ]; then 
-   Log  "[INSTALL]"  "Creating directory:$CNF_DATADIR/Moods"
-   mkdir $CNF_DATADIR/Moods >>/dev/null 2>>/dev/null
-fi
-
-# --------------
-# Checking FR Moods
-# --------------
-if [ ! -d $CNF_DATADIR/Moods/fr ]; then
-   mkdir $CNF_DATADIR/Moods/fr >>/dev/null 2>>/dev/null
-fi
-
-# --------------
-# Checking Apps 
-# --------------
-if [ ! -d $CNF_DATADIR/Apps ]; then
-   mkdir $CNF_DATADIR/Apps >>/dev/null 2>>/dev/null
-fi
-
-# --------------
-# Checking Apps Radios
-# --------------
-if [ ! -d $CNF_DATADIR/Apps/Streams ]; then
-   mkdir $CNF_DATADIR/Apps/Streams >>/dev/null 2>>/dev/null
-fi
-
-# --------------
-# Checking Apps Story
-# --------------
-if [ ! -d $CNF_DATADIR/Apps/Story ]; then
-   mkdir $CNF_DATADIR/Apps/Story >>/dev/null 2>>/dev/null
-fi
-
-if [ ! -d $CNF_DATADIR/Apps/Story/Data ]; then
-   mkdir $CNF_DATADIR/Apps/Story/Data >>/dev/null 2>>/dev/null
-fi
-
-# --------------
-# Checking crontab directories
-# --------------
-if [ ! -d /usr/spool ]; then
-   mkdir /usr/spool >>/dev/null 2>>/dev/null
-fi
-
-if [ ! -d /usr/spool/cron ]; then
-   mkdir /usr/spool/cron >>/dev/null 2>>/dev/null
-fi
-
-if [ ! -d /usr/spool/cron/crontabs ]; then
-   mkdir /usr/spool/cron/crontabs >>/dev/null 2>>/dev/null
-fi
-
-# --------------
-# Get local version
-# --------------
-if [ ! -f $TDIR/ok.version ]; then
-   LV=-1
-else
-   LV=$(cat $TDIR/ok.version  )
-fi
-
-# Create pipes for Program Control
-#if [ ! -f /tmp/mpd_control ]; then
-#   mknod /tmp/mpd_control p  >>/dev/null 2>>/dev/null
-#fi
-
-if [ ! -f /tmp/mplayer-control ]; then
-   Log  "[INSTALL]"  "Creating mplayer control pipe"
-   mknod /tmp/mplayer-control p  >>/dev/null 2>>/dev/null
-fi
-
-# Get server Version
-rm $TDIR/server.ok.version >>/dev/null 2>>/dev/null
-echo "----------------------------------------"
-Log  "[INSTALL]"  "Downloading $SURL/ok.version"
-cp ${RESSDIR}/ok.version $TDIR/server.ok.version
-if [ ! -e "$TDIR/server.ok.version" ] ; then
-  RV=0
-else
-  RV=$(cat $TDIR/server.ok.version )
-fi
-
-# Display version
-echo -n "Server Version : "
-Log  "[INSTALL]"  "Remote version : $RV"
-echo $RV
-echo -n "Local Version  : "
-echo $LV
-Log  "[INSTALL]"  "Local version : $LV"
-
-if [ "${LV:-0}" -ge "${RV:-0}" ] ; then
-	echo "----------------------------------------"
-  	echo "No update needed"
-else
-    # Update local version
-    rm -f $TDIR/ok.version >>/dev/null 2>>/dev/null
-    mv $TDIR/server.ok.version $TDIR/ok.version >>/dev/null 2>>/dev/null
-    echo "Web Root  : "$TDIR
-    echo "Data Root : "$UDIR 
-    
-    # Get Web Server Config File
-    echo "----------------------------------------"
-    echo "Updating Web Server Config"
-    echo "----------------------------------------"
-    Log  "[INSTALL]"  "Downloading $SURL/httpd.conf"
-echo "# define the server root. It will override -h  
-H:/usr/www  
-# 404 (not found) error page  
-# E404:/usr/www/404.html  
-# Show index.html when a directory is requested  
-I:index.html  
-" > /usr/httpd.conf
-     
-    echo "----------------------------------------"
-    echo "Updating startup Script"
-    echo "----------------------------------------"
-    if [ ! -e "/usr/yaffs_start.sh.backup.200" ]; then
-     Log  "[INSTALL]"  "Updating Startup Script"
-     cp /usr/yaffs_start.sh /usr/yaffs_start.sh.backup.200
-     cp /karotz/OkSetup/yaffs_start.sh /usr/yaffs_start.sh
-     chmod 777 /usr/yaffs_start.sh
-    fi
-        
-    # Updating /www
-    #URL=$1
-    #RDIR=$2
-    #LDIR=$3
-    #NAME=$4
-    #GROUP=$5
- 
-    # Creating cron path
-    #/var/spool/cron/crontabs
-    mkdir /var/spool >>/dev/null 2>>/dev/null
-    mkdir /var/spool/cron >>/dev/null 2>>/dev/null
-    mkdir /var/spool/cron/crontabs >>/dev/null 2>>/dev/null
-    
-    echo "Updating : Scripts"
-    echo "  Saving config"
-    mv -f $TDIR/cgi-bin/setup.inc $TDIR/cgi-bin/setup.inc.bak >>/dev/null 2>>/dev/null
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $SURL/www.zip"
-    cp ${RESSDIR}/www.zip /tmp/www.zip
-    if [ -e "/tmp/www.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/www.zip  -d /usr/www >>/dev/null 2>>/dev/null
-      rm -f /tmp/www.zip >>/dev/null 2>>/dev/null
-      echo "  Checking permissions"
-      chmod -R 777 /usr/www/cgi-bin >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-      exit 1
-    fi 
-    echo "----------------------------------------"
-    echo "Updating : Voices"
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $SURL/voice.zip"
-    cp ${RESSDIR}/voice.zip /tmp/voice.zip
-    if [ -e "/tmp/voice.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/voice.zip  -d $CNF_DATADIR/Voice >>/dev/null 2>>/dev/null
-      rm -f /tmp/voice.zip >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-      exit 1
-    fi
-    echo "----------------------------------------"
-    echo "Updating : Sounds"
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $SURL/sounds.zip"
-    cp ${RESSDIR}/sounds.zip /tmp/sounds.zip
-    if [ -e "/tmp/sounds.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/sounds.zip  -d $CNF_DATADIR/Sounds >>/dev/null 2>>/dev/null
-      rm -f /tmp/sounds.zip >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-       exit 1
-    fi
- 
-    echo "----------------------------------------"
-    echo "Updating : Radios"
-    echo "  Downloading"
-    Log  "[INSTALL]"  "Downloading $SURL/radios.zip"
-    cp ${RESSDIR}/radios.zip /tmp/radios.zip
-    if [ -e "/tmp/radios.zip" ]; then
-      echo "  Installing"
-      unzip  -o /tmp/radios.zip  -d $CNF_DATADIR/Apps/Streams >>/dev/null 2>>/dev/null
-      rm -f /tmp/radios.zip >>/dev/null 2>>/dev/null
-    else
-      echo "Download ERROR1. Exiting"
-      exit 1
-    fi 
-fi
 echo "----------------------------------------"
 echo  Done
 echo   You Must now manually Download Apps
 echo   from Update Tab
 echo "----------------------------------------"
-echo "Rabbit will restart to finish Instllation."
 
 Log  "[INSTALL]"  "Finished"
-Log  "[INSTALL]"  "Rebooting in 20 seconds"
-
-#/usr/bin/madplay $UDIR/Voice/install_ok.mp3 >>/dev/null 2>>/dev/null
-if [ -e "/tmp/end.mp3" ]; then
-  /usr/bin/madplay /tmp/end.mp3 >>/dev/null 2>>/dev/null
-fi
-
-killall led
-/karotz/bin/led -l $RED -p "000000" -d 700 &
-
-reboot -d 20
-
-
-
-
-
-
